
/**
 * pointclouds in this list will be shown on the pointcloud selection page.
 */
var pointclouds = {
//		"AsianDragon" : {
//				"name": 			"AsianDragon",
//				"label":			"Asian Dragon",
//				"url": 				"resources/pointClouds/asian_dragon/asian_dragon.js",
//				"iconUrl":			"resources/thumbnail/thumbAsianDragon.png",
//				"camPosition": 		[0,0,5],
//				"camLookAt":		[0,0,-1],
//				"illumination":		"phong",
//				"pointSize":		0.6,
//				"glossiness":		10,
//				"transform": 		[4, 0, 0, 0,
//				             		 0, 4, 0, 0,
//				             		 0, 0, 4, 0,
//				             		 0, 0, 0, 1]
//			},
			"Hand" : {
				"name": 			"Hand",
				"label":			"Hand",
				"url": 				"resources/pointClouds/hand/hand.js",
				"iconUrl":			"resources/thumbnail/hand.png",
				"camPosition": 		[0,0,5],
				"camLookAt":		[0,0,-1],
				"illumination":		"phong",
				"pointSize":		0.7,
				"glossiness":		10,
				"transform": 		[0.5, 	0, 		0, 		0,
				             		 0, 	0,		0.5, 	0,
				             		 0, 	-0.5, 	0, 		0,
				             		 -2, 	1, 		0, 		1]
			},
			"SkatePark" : {
				"name": 			"SkatePark",
				"label":			"Skatepark",
				"url": 				"resources/pointClouds/skate_40m/skate.js",
				"iconUrl":			"resources/thumbnail/skatepark.png",
				"camPosition": 		[-20,200,5],
				"camLookAt":		[0,0,-1],
				"illumination":		"flat",
				"pointSize":		1.0,
				"glossiness":		10,
				"transform": 		[-1, 0, 0, 0,
				             		 0, 0, 1, 0,
				             		 0, 1, 0, 0,
				             		 0, 0, 0, 1]
			},
			"Skate_spoct" : {
				"name": 			"Skate_spoct",
				"label":			"Skate_spoct",
				"url": 				"resources/pointClouds/skatepark/potree/skate_spoos/cloud.js",
				"iconUrl":			"resources/thumbnail/skatepark.png",
				"camPosition": 		[-20,200,5],
				"camLookAt":		[0,0,-1],
				"illumination":		"flat",
				"pointSize":		1.0,
				"glossiness":		10,
				"transform": 		[-1, 0, 0, 0,
				             		 0, 0, 1, 0,
				             		 0, 1, 0, 0,
				             		 0, 0, 0, 1]
			},
			"Tower" : {
				"name": 			"Tower",
				"label":			"Tower",
				"url": 				"resources/pointClouds/tower/potree/cloud.js",
				"iconUrl":			"resources/thumbnail/skatepark.png",
				"camPosition": 		[0,0,0],
				"camLookAt":		[0,0,-1],
				"illumination":		"flat",
				"pointSize":		0.2,
				"glossiness":		10,
				"transform": 		[-1, 0, 0, 0,
				             		 0, 0, 1, 0,
				             		 0, 1, 0, 0,
				             		 0, 0, 0, 1]
			},
			"Hall" : {
				"name": 			"Hall",
				"label":			"Hall",
				"url": 				"resources/pointClouds/hall/170m/cloud.js",
				"iconUrl":			"resources/thumbnail/skatepark.png",
				"camPosition": 		[442467,296,548525],
				"camLookAt":		[0,0,-1],
				"illumination":		"flat",
				"pointSize":		0.5,
				"glossiness":		10,
				"transform": 		[1, 0, 0, 0,
				             		 0, 0, 1, 0,
				             		 0, 1, 0, 0,
				             		 0, 0, 0, 1]
			},
			"Skate_Pcot_01" : {
				"name": 			"Skate_Pcot_01",
				"label":			"Skate_Pcot_01",
				"url": 				"resources/pointClouds/skatepark/40m/potree/cloud.js",
				"iconUrl":			"resources/thumbnail/skatepark.png",
				"camPosition": 		[-20,200,5],
				"camLookAt":		[0,0,-1],
				"illumination":		"flat",
				"pointSize":		1.0,
				"glossiness":		10,
				"transform": 		[-1, 0, 0, 0,
				             		 0, 0, 1, 0,
				             		 0, 1, 0, 0,
				             		 0, 0, 0, 1]
			}
		}